name: assignment-autotest-test
on: [push]
jobs:
    test:
        container: cuaesd/aesd-autotest:unit-test
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Checkout submodules
            run : git submodule update --init --recursive
          - name: Debug environment
            run: |
              echo "=== Environment Debug ==="
              pwd
              ls -la
              which bash
              which ruby
              which cmake
              which gcc
              echo "=== Script permissions ==="
              ls -la *.sh
          - name: Run unit test
            run: |
              chmod +x ./full-test.sh ./unit-test.sh ./test.sh
              bash ./full-test.sh
